[features]
seeds = true
skip-lint = false
[programs.localnet]
anchor_movie = "H1sxQUz8KLS2uy4j5peGUc8FvcPfoZeiAqt9iyT4XRuT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/thomascadle/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
