[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_movie = "5oYVhrRPbeUzBcvWADXXCgYSo9cF68RRdS4zyLoJe9Pe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/thomascadle/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
